name: CI/CD to EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::131676643044:role/build-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Images
        run: |
          for service in vote result worker; do
            IMAGE_URI=131676643044.dkr.ecr.us-east-1.amazonaws.com/ajay-ecr:${service}-latest
            echo "Building $service image..."
            docker build -t $IMAGE_URI ./$service
            docker push $IMAGE_URI
          done

      - name: Update Kubernetes Deployment
        run: |
          aws eks update-kubeconfig --name ajay-eks-test --region us-east-1
          kubectl apply -f k8s-specifications/
